# Generated by Django 3.2.8 on 2021-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211019_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odziezdamska',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='odziezmeska',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
