# Generated by Django 3.2.8 on 2021-10-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211019_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypUbraniaK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Typ',
                'verbose_name_plural': 'Typy',
            },
        ),
        migrations.RenameModel(
            old_name='TypUbrania',
            new_name='TypUbraniaM',
        ),
        migrations.AlterModelOptions(
            name='typubraniam',
            options={'verbose_name': 'Typ', 'verbose_name_plural': 'Typy'},
        ),
        migrations.RenameField(
            model_name='odziezmeska',
            old_name='typ',
            new_name='typM',
        ),
        migrations.AlterField(
            model_name='odziezdamska',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typubraniak'),
        ),
    ]
