# Generated by Django 3.2.8 on 2021-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211019_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odziezdamska',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='odziezmeska',
            name='typM',
        ),
        migrations.AddField(
            model_name='odziezdamska',
            name='type_womens_clothes',
            field=models.CharField(choices=[('SY', 'Spodenki'), ('CY', 'Joggery'), ('BY', 'Bluzy')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='odziezmeska',
            name='type_mens_clothes',
            field=models.CharField(choices=[('SX', 'Spodenki'), ('JX', 'Joggery'), ('BX', 'Bluzy')], default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='TypUbraniaK',
        ),
        migrations.DeleteModel(
            name='TypUbraniaM',
        ),
    ]
