# Generated by Django 3.2.8 on 2021-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211022_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mens_clothes', models.CharField(choices=[('SX', 'Spodenki'), ('JX', 'Joggery'), ('BX', 'Bluzy')], default='SX', max_length=100)),
                ('nazwa', models.CharField(max_length=120)),
                ('rozmiar', models.CharField(max_length=4)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kolor', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Odziez Meska',
                'verbose_name_plural': 'Odziez Meska',
            },
        ),
        migrations.CreateModel(
            name='WomansClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_womens_clothes', models.CharField(choices=[('SY', 'Spodenki'), ('CY', 'Joggery'), ('BY', 'Bluzy')], default='SY', max_length=100)),
                ('nazwa', models.CharField(max_length=120)),
                ('rozmiar', models.CharField(max_length=4)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kolor', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Odziez Damska',
                'verbose_name_plural': 'Odziez Damska',
            },
        ),
        migrations.DeleteModel(
            name='OdziezDamska',
        ),
        migrations.DeleteModel(
            name='OdziezMeska',
        ),
    ]
